version: '3'

services:
  django:
    container_name: django
    build:
      context: .
      dockerfile: auth/Dockerfile
      target: dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./auth:/app
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    depends_on:
      - broker
      - database

  broker:
    image: redis
    restart: on-failure
    ports:
      - "6379:6379"

  celery:
    build:
      context: ./
      dockerfile: auth/Dockerfile
      target: dev
    command: celery -A project worker --beat --scheduler django --loglevel=info
    restart: on-failure
    volumes:
      - ./auth:/app
    depends_on:
      - broker
      - database
    env_file:
      - .env.dev

  database:
    image: 'postgres:latest'

    ports:
      - 5432:5432

    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: game_server # The PostgreSQL default database (automatically created at first launch)