# Generated by Django 4.1.4 on 2023-03-14 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Name')),
                ('color', models.CharField(max_length=10, verbose_name='Color')),
                ('token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.token')),
            ],
            options={
                'verbose_name': 'Character',
                'verbose_name_plural': 'Characteres',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.PositiveIntegerField(verbose_name='Item Name')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('source', models.CharField(max_length=32, verbose_name='Source')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.character')),
            ],
            options={
                'verbose_name': 'Inventory',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.PositiveIntegerField(verbose_name='Item ID')),
                ('item_slot', models.PositiveSmallIntegerField(verbose_name='Slot')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='world.character')),
            ],
            options={
                'verbose_name': 'Equipment',
                'unique_together': {('character', 'item_slot')},
            },
        ),
    ]
