# Generated by Django 4.1.4 on 2023-03-16 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sessionmap',
            old_name='character',
            new_name='token',
        ),
    ]
