# Generated by Django 4.1.4 on 2023-03-16 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
        ('account', '0003_remove_sessionmap_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionmap',
            name='character',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='world.character'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sessionmap',
            name='token',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.token'),
            preserve_default=False,
        ),
    ]
